import assert from "node:assert/strict";
import { describe, it } from "node:test";
import {
  checkVersionMirrors,
  parseVersion,
  readCargoLockVersion,
  readCargoTomlVersion,
  readPackageJsonVersion,
  rewriteCargoLockVersion,
  rewriteCargoTomlVersion,
  rewritePackageJsonVersion,
} from "./desktop-version.ts";

const CARGO_TOML = `[package]
name = "openvids-desktop"
version = "0.1.0"
edition = "2021"
rust-version = "1.77.2"

[package.metadata.bundle]
version = "9.9.9"

[dependencies]
tauri = { version = "2", features = [] }
serde = "1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
`;

const CARGO_LOCK = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "libc"
version = "0.2.174"

[[package]]
name = "openvids-desktop"
version = "0.1.0"
dependencies = [
 "getrandom 0.3.4",
 "libc",
 "tauri",
]

[[package]]
name = "tauri"
version = "2.9.1"
`;

const PACKAGE_JSON = `{
  "name": "@openvids/desktop",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "tauri": "tauri"
  }
}
`;

const SOURCES = {
  cargoToml: CARGO_TOML,
  cargoLock: CARGO_LOCK,
  packageJson: PACKAGE_JSON,
  tauriConf: "{}\n",
};

function changedLines(before: string, after: string): string[] {
  const beforeLines = before.split("\n");
  const afterLines = after.split("\n");
  assert.equal(afterLines.length, beforeLines.length);
  return beforeLines.flatMap((line, index) =>
    line === afterLines[index] ? [] : [`${line} -> ${afterLines[index] ?? ""}`],
  );
}

describe("parseVersion", () => {
  it("accepts bare semver, prereleases and build metadata", () => {
    assert.equal(parseVersion("0.1.0"), "0.1.0");
    assert.equal(parseVersion(" 1.2.3 "), "1.2.3");
    assert.equal(parseVersion("1.2.0-rc.1"), "1.2.0-rc.1");
    assert.equal(parseVersion("2.0.0+build.7"), "2.0.0+build.7");
  });

  it("rejects a leading v, partial versions, leading zeros and junk", () => {
    for (const value of ["v1.2.3", "1.2", "1.2.3.4", "01.2.3", "1.2.3-", "abc", "", " "]) {
      assert.throws(() => parseVersion(value), /invalid version/);
    }
  });
});

describe("Cargo.toml version", () => {
  it("reads the [package] version, not a dependency or metadata version", () => {
    assert.equal(readCargoTomlVersion(CARGO_TOML), "0.1.0");
    assert.equal(
      readCargoTomlVersion(CARGO_TOML.replace('version = "0.1.0"', 'version = "0.2.0"')),
      "0.2.0",
    );
  });

  it("rewrites only the [package] version line", () => {
    const next = rewriteCargoTomlVersion(CARGO_TOML, "0.1.1");
    assert.deepEqual(changedLines(CARGO_TOML, next), ['version = "0.1.0" -> version = "0.1.1"']);
    assert.equal(readCargoTomlVersion(next), "0.1.1");
    assert.match(next, /^version = "9\.9\.9"$/m);
    assert.match(next, /^rust-version = "1\.77\.2"$/m);
    assert.match(next, /^tauri = \{ version = "2", features = \[\] \}$/m);
  });

  it("throws when there is no version in a [package] table", () => {
    assert.throws(() => readCargoTomlVersion('[dependencies]\nversion = "1"\n'), /\[package\]/);
    assert.throws(
      () => rewriteCargoTomlVersion('[dependencies]\nversion = "1"\n', "0.1.1"),
      /\[package\]/,
    );
  });
});

describe("Cargo.lock version", () => {
  it("reads the openvids-desktop entry among other packages", () => {
    assert.equal(readCargoLockVersion(CARGO_LOCK), "0.1.0");
  });

  it("rewrites only that entry's version line", () => {
    const next = rewriteCargoLockVersion(CARGO_LOCK, "0.1.1");
    assert.deepEqual(changedLines(CARGO_LOCK, next), ['version = "0.1.0" -> version = "0.1.1"']);
    assert.equal(readCargoLockVersion(next), "0.1.1");
    assert.match(next, /^version = 4$/m);
    assert.match(next, /^name = "tauri"\nversion = "2\.9\.1"$/m);
    assert.match(next, /^name = "libc"\nversion = "0\.2\.174"$/m);
  });

  it("throws when the entry is missing", () => {
    const lock = CARGO_LOCK.replace('name = "openvids-desktop"', 'name = "something-else"');
    assert.throws(() => readCargoLockVersion(lock), /openvids-desktop/);
    assert.throws(() => rewriteCargoLockVersion(lock, "0.1.1"), /openvids-desktop/);
  });
});

describe("package.json version", () => {
  it("rewrites only the version and keeps formatting and the trailing newline", () => {
    const next = rewritePackageJsonVersion(PACKAGE_JSON, "0.1.1");
    assert.deepEqual(changedLines(PACKAGE_JSON, next), [
      '  "version": "0.1.0", ->   "version": "0.1.1",',
    ]);
    assert.equal(next, PACKAGE_JSON.replace('"version": "0.1.0"', '"version": "0.1.1"'));
    assert.equal(readPackageJsonVersion(next), "0.1.1");
    assert.ok(next.endsWith("}\n"));
  });

  it("keeps a file without a trailing newline as it is", () => {
    const next = rewritePackageJsonVersion(PACKAGE_JSON.trimEnd(), "0.1.1");
    assert.equal(next.endsWith("\n"), false);
    assert.ok(next.endsWith("}"));
  });

  it("throws when the version is missing or not a string", () => {
    assert.throws(() => readPackageJsonVersion('{"name":"x"}'), /version/);
    assert.throws(() => readPackageJsonVersion('{"version":1}'), /version/);
    assert.throws(() => rewritePackageJsonVersion("[]", "0.1.1"), /JSON object/);
  });
});

describe("checkVersionMirrors", () => {
  it("accepts consistent mirrors", () => {
    assert.deepEqual(checkVersionMirrors(SOURCES), { version: "0.1.0", problems: [] });
  });

  it("names each disagreeing mirror", () => {
    const badLock = CARGO_LOCK.replace(
      'name = "openvids-desktop"\nversion = "0.1.0"',
      'name = "openvids-desktop"\nversion = "0.1.2"',
    );
    const badPackage = PACKAGE_JSON.replace('"version": "0.1.0"', '"version": "0.1.2"');
    const confWithVersion = '{"version": "0.1.0"}\n';

    assert.deepEqual(checkVersionMirrors({ ...SOURCES, cargoLock: badLock }).problems, [
      "apps/desktop/src-tauri/Cargo.lock: the openvids-desktop entry is 0.1.2, expected 0.1.0 (from apps/desktop/src-tauri/Cargo.toml)",
    ]);
    assert.deepEqual(checkVersionMirrors({ ...SOURCES, packageJson: badPackage }).problems, [
      'apps/desktop/package.json: "version" is 0.1.2, expected 0.1.0 (from apps/desktop/src-tauri/Cargo.toml)',
    ]);
    assert.deepEqual(checkVersionMirrors({ ...SOURCES, tauriConf: confWithVersion }).problems, [
      'apps/desktop/src-tauri/tauri.conf.json: remove "version" so Tauri reads the version from apps/desktop/src-tauri/Cargo.toml',
    ]);

    const all = checkVersionMirrors({
      cargoToml: CARGO_TOML,
      cargoLock: badLock,
      packageJson: badPackage,
      tauriConf: confWithVersion,
    });
    assert.equal(all.problems.length, 3);
  });

  it("throws when the Cargo.toml baseline itself is not valid semver", () => {
    const badToml = CARGO_TOML.replace('version = "0.1.0"', 'version = "0.1"');
    assert.throws(() => checkVersionMirrors({ ...SOURCES, cargoToml: badToml }), /invalid version/);
  });
});

describe("platform overlay versions", () => {
  it("accepts overlays without a version", () => {
    assert.deepEqual(
      checkVersionMirrors({
        ...SOURCES,
        tauriWindowsConf: '{"bundle":{"targets":["nsis"]}}',
        tauriMacosConf: '{"bundle":{"targets":["app","dmg"]}}',
        tauriProdConf: '{"bundle":{"resources":{}}}',
      }),
      { version: "0.1.0", problems: [] },
    );
  });

  it("flags a version in any overlay config", () => {
    const withVersion = '{"version": "0.1.0"}';
    for (const key of ["tauriWindowsConf", "tauriMacosConf", "tauriProdConf"] as const) {
      const problems = checkVersionMirrors({ ...SOURCES, [key]: withVersion }).problems;
      assert.equal(problems.length, 1);
      assert.match(problems[0] ?? "", /remove "version"/);
    }
  });

  it("treats missing overlays as no problem", () => {
    assert.deepEqual(checkVersionMirrors(SOURCES), { version: "0.1.0", problems: [] });
  });
});
